project:
  type: website
  output-dir: docs

website:
  title: "AQUACOSM ECR Network"
  site-url: https://aquacosm-ecr.github.io/
  navbar:
    pinned: true
    title: false
    logo: images/AQUACOSM-ecr_transpaternt.png
    
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: events.qmd
        text: Events
      - href: newsletter.qmd
        text: Newsletters
      - href: contact.qmd
        text: Contact
        
    right:
      - text: "{{< iconify fa6-brands bluesky size=1.1em title='Bluesky' >}}"
        href: https://bsky.app/profile/aquacosm-ecr.bsky.social
      - icon: discord
        href: https://discord.gg/MZsfj6E5xd
        
    search: false
    
  page-footer:
    left: We have recieved funding from the EU H2020-INFRAIA project AQUACOSM-plus (No. 871081) 
    right: This website is built with [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/aquacosm-ecr/aquacosm-ecr.github.io), {{< fa brands r-project title="R Project" >}} and [Quarto](https://quarto.org/)

format:
  html:
    theme: 
      - simplex
      - styles.scss
    mainfont: Aleo
    page-layout: full
    toc: false
